In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# vocabulary size
voc_size = 10000

## One Hot Representation

In [5]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[468, 5267, 1187, 6228], [468, 5267, 1187, 1155], [468, 5186, 1187, 2481], [7807, 6669, 3226, 6995, 9046], [7807, 6669, 3226, 6995, 3829], [9853, 468, 588, 1187, 8085], [124, 3305, 317, 6995]]


## Word Embeddin Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_len=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0  468 5267 1187 6228]
 [   0    0    0    0  468 5267 1187 1155]
 [   0    0    0    0  468 5186 1187 2481]
 [   0    0    0 7807 6669 3226 6995 9046]
 [   0    0    0 7807 6669 3226 6995 3829]
 [   0    0    0 9853  468  588 1187 8085]
 [   0    0    0    0  124 3305  317 6995]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 62ms/step
[[[-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991
   -0.04248058  0.04999726  0.03252074  0.00250923  0.02346803]
  [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991
   -0.04248058  0.04999726  0.03252074  0.00250923  0.02346803]
  [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991
   -0.04248058  0.04999726  0.03252074  0.00250923  0.02346803]
  [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991
   -0.04248058  0.04999726  0.03252074  0.00250923  0.02346803]
  [-0.00656959 -0.04959217  0.03617695  0.01866761  0.03546386
   -0.03178438 -0.01398708 -0.01992518 -0.0395468  -0.02117627]
  [-0.04750959 -0.00494195 -0.04987968 -0.04475227 -0.02411596
   -0.04431398  0.04493132  0.02535099 -0.03672332 -0.02319927]
  [-0.04569558 -0.00471842  0.02578962  0.04474065  0.01785754
    0.02138186 -0.00266946  0.00010068  0.03405012  0.02853233]
  [-0.0327509   0.0342144  -0.02660826 -0.0404645  -0.00711

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0,  468, 5267, 1187, 6228], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 23ms/step
[[-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991 -0.04248058
   0.04999726  0.03252074  0.00250923  0.02346803]
 [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991 -0.04248058
   0.04999726  0.03252074  0.00250923  0.02346803]
 [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991 -0.04248058
   0.04999726  0.03252074  0.00250923  0.02346803]
 [-0.0122598  -0.02246401  0.03583015  0.02321224 -0.00976991 -0.04248058
   0.04999726  0.03252074  0.00250923  0.02346803]
 [-0.00656959 -0.04959217  0.03617695  0.01866761  0.03546386 -0.03178438
  -0.01398708 -0.01992518 -0.0395468  -0.02117627]
 [-0.04750959 -0.00494195 -0.04987968 -0.04475227 -0.02411596 -0.04431398
   0.04493132  0.02535099 -0.03672332 -0.02319927]
 [-0.04569558 -0.00471842  0.02578962  0.04474065  0.01785754  0.02138186
  -0.00266946  0.00010068  0.03405012  0.02853233]
 [-0.0327509   0.0342144  -0.02660826 -0.0404645  -0.00711067  0.03718309